name: RType CI

on:
  push:
    branches: [ "main", "test_conan" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conan (Unix)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y python3-pip ninja-build
          pip install conan

      - name: Install Conan (Windows)
        if: matrix.os == 'windows-latest'
        run: pip install conan

      - name: Install dependencies (Unix)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y build-essential ninja-build

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install ninja

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja
          
      - name: Build project
        if: matrix.os == 'ubuntu-latest'
        run: ./build.sh

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: rtype_build_${{ matrix.os }}
          path: build/
